# name: Automated API tests using Postman CLI

# on: push

# jobs:
#   automated-api-tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install Postman CLI
#         run: |
#           curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
#       - name: Login to Postman CLI
#         run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
#       - name: Run API tests
#         run: |
#           postman collection run "17473675-ef4255b8-26ef-449c-bf37-851f88707ee0"

name: Run Postman Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Newman tests and generate HTML report
        run: |
          npx newman run collection.json \
            -r cli,html \
            --reporter-html-export newman-report.html


      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html
